webtalk_init -webtalk_dir /home/oliver/uni/m1_embedded_systems/projekt/vhdl/encrypt/encrypt.sim/sim_1/behav/xsim/xsim.dir/tb_encrypt_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jun 16 22:50:38 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211359530_1777543984_210703551_408" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0e5800a3-8775-4580-8d91-c42eaed2fa81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b8c5163dd87f45f28bbb0cceb33b7a7a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "113" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500.058 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "100 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "10.63_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "164284_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1999447305 -regid "211359530_1777543984_210703551_408" -xml /home/oliver/uni/m1_embedded_systems/projekt/vhdl/encrypt/encrypt.sim/sim_1/behav/xsim/xsim.dir/tb_encrypt_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/oliver/uni/m1_embedded_systems/projekt/vhdl/encrypt/encrypt.sim/sim_1/behav/xsim/xsim.dir/tb_encrypt_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/oliver/uni/m1_embedded_systems/projekt/vhdl/encrypt/encrypt.sim/sim_1/behav/xsim/xsim.dir/tb_encrypt_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
