#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jun 16 22:46:43 CEST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b8c5163dd87f45f28bbb0cceb33b7a7a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_encrypt_behav xil_defaultlib.tb_encrypt -log elaborate.log"
xelab -wto b8c5163dd87f45f28bbb0cceb33b7a7a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_encrypt_behav xil_defaultlib.tb_encrypt -log elaborate.log

